## Data Collection Notebook

In [1]:
import json
import os

import numpy as np
import pandas as pd
from pandas.api.types import CategoricalDtype

<div style="padding: 0px 0px 0px 20px; border-left: 8px solid #ED9255; border-radius: 8px">
<h3>
    Reading csv

</h3>



</div>

In [2]:
rurality_path = os.path.abspath(os.path.join("NBO1_Data_Collection.ipynb/"+"../.."+"/data/raw/attainment_by_rurality.csv"))
chars_path = os.path.abspath(os.path.join("NBO1_Data_Collection.ipynb/"+"../.."+"/data/raw/attainment_by_characteristics.csv"))

In [3]:
rurality_df = pd.read_csv(rurality_path)
chars_df = pd.read_csv(chars_path)

<div style="padding: 0px 0px 0px 20px; border-left: 8px solid #ED9255; border-radius: 8px">
<h3>
    Pulling important columns only

</h3>



</div>

In [4]:
chars_df = chars_df[["time_period", "version", "region_name", "characteristic_type", "characteristic_value",
    "establishment_type", "number_of_students_acad", "number_of_students_alev", "number_of_students_potential",
    "aps_per_entry_grade_acad", "aps_per_entry_grade_alev", "pc_achieving_3_astar_to_a_alev"]]
chars_df

,time_period,version,region_name,characteristic_type,characteristic_value,establishment_type,number_of_students_acad,number_of_students_alev,number_of_students_potential,aps_per_entry_grade_acad,aps_per_entry_grade_alev,pc_achieving_3_astar_to_a_alev
0,201920,Final,South East,Sex,Female,All state-funded schools and colleges,4317,4272,8343,B,B,18.097
1,201920,Final,East of England,Sex,Female,All state-funded schools and colleges,3888,3786,6977,B,B,25.079
2,201920,Final,South East,Sex,Female,All state-funded schools and colleges,4279,3786,8119,B,B,23.546
3,201920,Final,North West,Sex,Female,All state-funded schools and colleges,2486,2438,5728,B,B,20.884
4,201920,Final,East Midlands,Sex,Female,All state-funded schools and colleges,1400,1387,2672,B,B,19.161
...,...,...,...,...,...,...,...,...,...,...,...,...
21029,202324,Revised,South East,All Students,All state-funded students,All state-funded schools and colleges,49986,48375,95158,B-,B-,15.976
21030,202324,Revised,East of England,All Students,All state-funded students,All state-funded schools and colleges,31366,30773,67239,C+,C+,14.403
21031,202324,Revised,London,All Students,All state-funded students,All state-funded schools and colleges,48514,47533,87911,B-,B-,16.177
21032,202324,Revised,North West,All Students,All state-funded students,All state-funded schools and colleges,33343,32853,78493,C+,C+,14.52
21033,202324,Revised,Yorkshire and The Humber,All Students,All state-funded students,All state-funded schools and colleges,23499,23136,57419,C+,C+,13.527

In [5]:
chars_df.isna().sum()

time_period                       0
version                           0
region_name                       0
characteristic_type               0
characteristic_value              0
establishment_type                0
number_of_students_acad           0
number_of_students_alev           0
number_of_students_potential      0
aps_per_entry_grade_acad          0
aps_per_entry_grade_alev          0
pc_achieving_3_astar_to_a_alev    0
dtype: int64

In [19]:
chars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21034 entries, 0 to 21033
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   time_period                     21034 non-null  int64
 1   version                         21034 non-null  object
 2   region_name                     21034 non-null  object
 3   characteristic_type             21034 non-null  object
 4   characteristic_value            21034 non-null  object
 5   establishment_type              21034 non-null  object
 6   number_of_students_acad         20840 non-null  float64
 7   number_of_students_alev         20830 non-null  float64
 8   number_of_students_potential    21009 non-null  float64
 9   aps_per_entry_grade_acad        20363 non-null  object
 10  aps_per_entry_grade_alev        20346 non-null  object
 11  pc_achieving_3_astar_to_a_alev  20399 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 1.9+ MB

<div style="padding: 0px 0px 0px 20px; border-left: 8px solid #ED9255; border-radius: 8px">
<h3>
    Dealing with custom null values "z", "x" and "c" and column types to indentify actual nulls

</h3>



</div>

In [7]:
def setNulls(x):
    if x in ["z", "x", "c"]:
        return np.nan
    else:
        try:
            return pd.to_numeric(x)
        except (ValueError, TypeError):
            return x

chars_df = chars_df.map(setNulls)

chars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21034 entries, 0 to 21033
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   time_period                     21034 non-null  int64
 1   version                         21034 non-null  object
 2   region_name                     21034 non-null  object
 3   characteristic_type             21034 non-null  object
 4   characteristic_value            21034 non-null  object
 5   establishment_type              21034 non-null  object
 6   number_of_students_acad         20840 non-null  float64
 7   number_of_students_alev         20830 non-null  float64
 8   number_of_students_potential    21009 non-null  float64
 9   aps_per_entry_grade_acad        20363 non-null  object
 10  aps_per_entry_grade_alev        20346 non-null  object
 11  pc_achieving_3_astar_to_a_alev  20399 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 1.9+ MB

In [8]:
chars_df.isna().sum()

time_period                         0
version                             0
region_name                         0
characteristic_type                 0
characteristic_value                0
establishment_type                  0
number_of_students_acad           194
number_of_students_alev           204
number_of_students_potential       25
aps_per_entry_grade_acad          671
aps_per_entry_grade_alev          688
pc_achieving_3_astar_to_a_alev    635
dtype: int64

<div style="padding: 0px 0px 0px 20px; border-left: 8px solid #ED9255; border-radius: 8px">
<h3>
    Giving functional order to grade letters A*, A, B etc.

</h3>



</div>

In [9]:
chars_df["aps_per_entry_grade_alev"].unique()

array(['B', 'B-', 'A-', 'B+', nan, 'C+', 'C', 'C-', 'D+', 'A', 'A*-', 'D',
       'A+', 'A*', 'D-', 'E-', 'E+', 'E', 'U'], dtype=object)

In [10]:
chars_df["aps_per_entry_grade_acad"].unique()

array(['B', 'B-', 'A-', 'B+', nan, 'C+', 'C', 'C-', 'D+', 'A', 'A*-',
       'A+', 'A*', 'D', 'E+', 'E-', 'D-', 'E', 'U'], dtype=object)

In [24]:
def setup_categorical_type(col):
    chars_df[col] = chars_df[col].fillna('N/A')
    
    grade_order = CategoricalDtype(categories=['A*', 'A*-', 'A+', 'A', 'A-',
                                               'B+', 'B', 'B-', 'C+', 'C',
                                               'C-', 'D+', 'D', 'D-', 'E+',
                                               'E', 'E-', 'U' , 'N/A'], ordered=True)
    
    chars_df[col] = chars_df[col].astype(grade_order)


setup_categorical_type("aps_per_entry_grade_acad")
setup_categorical_type("aps_per_entry_grade_alev")

chars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21034 entries, 0 to 21033
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   time_period                     21034 non-null  int64
 1   version                         21034 non-null  object
 2   region_name                     21034 non-null  object
 3   characteristic_type             21034 non-null  object
 4   characteristic_value            21034 non-null  object
 5   establishment_type              21034 non-null  object
 6   number_of_students_acad         20840 non-null  float64
 7   number_of_students_alev         20830 non-null  float64
 8   number_of_students_potential    21009 non-null  float64
 9   aps_per_entry_grade_acad        21034 non-null  category
 10  aps_per_entry_grade_alev        21034 non-null  category
 11  pc_achieving_3_astar_to_a_alev  20399 non-null  float64
dtypes: category(2), float64(4), int64(1), object(5)
memory usage: 1.6+ MB

In [25]:
chars_df["characteristic_type"].unique()

array(['Sex', 'First Language', 'FSM', 'SEN Provision', 'Ethnicity',
       'Prior Attainment', 'Disadvantage', 'All Students'], dtype=object)

In [60]:
grouped = chars_df[(chars_df["characteristic_type"]=="Sex")].groupby(
    ["region_name", "characteristic_value"]).agg({
    "number_of_students_acad":"sum",
    "number_of_students_alev": "sum",
    "number_of_students_potential": "sum",
    "aps_per_entry_grade_acad": lambda x: x.mode()[0],
    "aps_per_entry_grade_alev": lambda x: x.mode()[0]
    })

total_row = grouped.sum(numeric_only=True)
total_row.name = 'Total'
grouped_with_total = pd.concat([grouped, total_row.to_frame().T])

grouped_with_total

,number_of_students_acad,number_of_students_alev,number_of_students_potential,aps_per_entry_grade_acad,aps_per_entry_grade_alev
"(East Midlands, Female)",107186.0,106470.0,203088.0,C+,C+
"(East Midlands, Male)",84845.0,83898.0,199725.0,B-,B-
"(East of England, Female)",161977.0,159012.0,314464.0,B-,B
"(East of England, Male)",135097.0,132050.0,323852.0,B-,B-
"(London, Female)",249560.0,245417.0,420217.0,B,B
"(London, Male)",203643.0,198747.0,435157.0,B-,B-
"(North East, Female)",54850.0,54334.0,142544.0,B,B
"(North East, Male)",41549.0,40960.0,142984.0,C+,C+
"(North West, Female)",178377.0,176077.0,376336.0,B,B
"(North West, Male)",138673.0,135961.0,370515.0,B-,B-
"(South East, Female)",255204.0,247524.0,451010.0,B,B
"(South East, Male)",217291.0,209350.0,461081.0,B-,B-
"(South West, Female)",124925.0,122872.0,254731.0,B,B
"(South West, Male)",102039.0,99463.0,255997.0,C+,B-
"(West Midlands, Female)",145387.0,143915.0,309985.0,B-,B-
"(West Midlands, Male)",112616.0,110515.0,308949.0,B-,B-
"(Yorkshire and The Humber, Female)",125619.0,124395.0,276271.0,B,B
"(Yorkshire and The Humber, Male)",96061.0,94198.0,272490.0,B-,B-
Total,2534899.0,2485158.0,5519396.0,NaN,NaN